import React from 'react';
import ImgComp from "../ImgComp/ImgComp";

const Home = () => {
  return (
    <div>
      Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime enim dignissimos minima. Ipsa ut deserunt repellat impedit rerum excepturi sapiente, debitis tenetur? Laudantium, exercitationem minus modi excepturi recusandae corporis hic.
      <ImgComp />
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae nobis vero fugit, possimus nulla rem obcaecati dolores blanditiis repudiandae enim recusandae dignissimos natus, ex ea nostrum? Vel atque excepturi assumenda.
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas maxime assumenda voluptate sit dicta sed excepturi odit velit ad similique beatae aliquid quos, iure, quas nisi accusamus ea! Dolore provident velit tempora!
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis quod aperiam officiis voluptas dicta cum placeat et, reprehenderit a sapiente! Sequi excepturi odio earum, 
      voluptatum adipisci assumenda quisquam quaerat, nobis repellat numquam vel recusandae qui accusamus? Nam tenetur quidem nesciunt at voluptas doloribus vero eius iure, expedita ex placeat illo, ea nisi hic soluta. Amet, dolore accusantium dolorem tenetur deserunt error nihil sint ab cumque aspernatur, minima asperiores! Repellat voluptas
      <ImgComp /> 
      mollitia expedita nulla? Labore reprehenderit at voluptatum reiciendis repudiandae sunt incidunt a voluptate corrupti consectetur quia sed accusamus est et non recusandae, tenetur distinctio, atque dolorem, autem laborum soluta. Voluptate, quae accusantium! Sint, atque voluptatem esse aliquam quo ad iusto nam? Totam, beatae quae magnam hic nesciunt debitis assumenda minima maiores, eveniet et unde recusandae? Ut dolorum nulla, qui ratione delectus, totam suscipit nihil sapiente, asperiores distinctio ipsam. Magni atque est cumque asperiores. Veritatis id libero ratione magnam rerum praesentium quia nisi atque corporis! Nisi nulla ad iure earum, molestias voluptatem! Corporis corrupti soluta maiores dolor blanditiis omnis et sit odit quos! Cumque enim id hic repellendus consequatur iusto, 
      <ImgComp />
      voluptatibus laboriosam? Blanditiis facere reiciendis cumque minima, expedita dicta quisquam harum facilis explicabo molestias vero labore placeat quaerat voluptatum accusamus a commodi ducimus quis dolores optio animi maxime iusto quas. Numquam eligendi aliquam in repudiandae minima soluta exercitationem, molestiae expedita blanditiis saepe voluptatum, explicabo dolores provident temporibus pariatur, esse ipsam. Minima reiciendis soluta deserunt ratione harum fugiat repellat adipisci sapiente magni ut temporibus aliquid nisi incidunt ex doloribus consequuntur voluptas esse pariatur, eius alias error molestias voluptatibus possimus. Possimus adipisci exercitationem suscipit sed ducimus harum, enim laudantium iusto nostrum, laborum natus aliquid quibusdam aliquam nisi tenetur optio? Quod,
      <ImgComp />
       molestiae, doloremque ratione nihil veniam porro sequi reiciendis rem nobis, ipsam est molestias. Fuga harum doloribus eius. Voluptatem maiores autem illum assumenda corporis sunt a doloremque consequuntur, aspernatur accusamus reiciendis quae? Impedit quis fugit ad ipsum nisi pariatur expedita quod saepe fugiat placeat assumenda minus ducimus, debitis illo consequatur enim eos officia cum obcaecati ut, provident quos quidem voluptate. Odio aspernatur nostrum similique quod iusto, excepturi deleniti, exercitationem, vitae dignissimos porro nam saepe voluptas adipisci vel non nisi distinctio maxime. Architecto aliquam laudantium eius repudiandae veritatis
      <ImgComp />
        consequuntur enim. Laboriosam, voluptates alias fuga provident reiciendis illum, quidem culpa sit eveniet voluptatum consectetur temporibus facilis expedita nobis, quibusdam quas dolorum? Voluptates quam dolorem facilis laborum optio, esse id temporibus sunt alias magnam voluptas saepe quasi soluta incidunt aliquam nostrum sint autem. Non, veritatis quia fugit ipsa sapiente quisquam velit? Cum mollitia amet a voluptatem, illo ducimus assumenda iste voluptate eaque ipsam molestiae, laborum ea nemo aperiam architecto hic magnam inventore dicta velit distinctio commodi tempora. Rem culpa unde magnam id sunt, fuga odit omnis, illo quibusdam cumque possimus vero soluta repudiandae eum dolor architecto magni dolores ut 
      <ImgComp />
       distinctio dolorum corporis earum fugit? Quisquam corporis odio eius aliquid aspernatur ut enim exercitationem excepturi sed reprehenderit! Blanditiis ea inventore dolorem veritatis repudiandae eveniet fugit labore suscipit hic accusantium magni eaque quisquam itaque, enim nam facilis beatae pariatur ducimus eligendi et soluta atque exercitationem perferendis! Ut, animi fuga totam minima aliquam, nostrum dolorem sit nemo expedita ratione illo a quaerat laborum? Ullam labore consequuntur sapiente, soluta dolorem cumque tempore! Quasi magni nam assumenda exercitationem amet cum voluptatibus reiciendis minus porro recusandae accusantium sed excepturi earum est alias eos quibusdam similique modi id harum cumque, dignissimos voluptatem sequi atque. Quaerat, vel. Ex harum temporibus autem quod earum quisquam ipsam, ullam veritatis facilis, vero tempore atque rem? Velit dolor ullam a reiciendis 
      <ImgComp />
       dolorem, temporibus, dicta rem incidunt magnam omnis vero assumenda! Reiciendis deserunt corrupti distinctio nulla incidunt dolorem laboriosam eveniet labore, quia illo facere molestias dolorum inventore assumenda dolore ipsa, at harum pariatur sapiente ipsam minus! Amet, ratione nam magnam sed similique eius nostrum, omnis fugit est velit, magni nesciunt vel debitis nisi deleniti minima natus. Incidunt eaque sapiente rerum tenetur nesciunt corrupti laborum quo, commodi ea veritatis ab officia provident assumenda mollitia molestiae soluta neque adipisci possimus inventore pariatur quidem excepturi amet explicabo! Unde est perferendis soluta vitae officiis fugit aut incidunt, esse mollitia ipsum tempore reprehenderit eaque laboriosam tempora beatae nostrum aperiam consequatur ratione suscipit error similique aliquam enim quam obcaecati? Rerum deserunt dolore ex, nulla explicabo nobis fuga sit ad voluptas velit facere. Mollitia repudiandae totam earum error neque nemo quibusdam, qui laboriosam a nesciunt. Aliquid unde 
      <ImgComp />
       deserunt, optio expedita labore deleniti assumenda fugit fuga eveniet culpa quisquam! Id impedit quas enim, sapiente quisquam veniam quaerat tenetur dolorem quia in ut vitae aut assumenda maiores quos voluptate nesciunt accusantium quidem eum modi cum? Earum obcaecati distinctio ut eos nam sequi neque facilis commodi incidunt error voluptate, excepturi libero? Qui, sit in ab fugiat eaque dolorum odit sunt ullam accusantium nostrum architecto quia! Blanditiis eius placeat eligendi perspiciatis numquam quisquam magni quibusdam corporis nobis eaque accusantium quo autem repellat quod earum ducimus nostrum, dicta omnis mollitia non assumenda! Assumenda aperiam odit nesciunt, sequi corrupti necessitatibus possimus delectus provident repellendus et quo harum distinctio expedita inventore consequuntur temporibus molestias ipsam quia. Repellat molestias delectus adipisci consectetur esse? Consequuntur neque explicabo eligendi officia dolorem eveniet adipisci voluptatibus in excepturi vel fuga hic totam architecto tempora, libero asperiores perspiciatis ut repellat 
      <ImgComp />
       molestias reprehenderit! Illo omnis necessitatibus dolorem culpa tempore laborum eligendi explicabo voluptas voluptate consequuntur maiores distinctio animi tenetur odio soluta, quisquam reiciendis suscipit perferendis? Earum iusto error repellendus veniam molestiae deserunt rem laboriosam soluta dolore minus numquam nihil illum, maiores ullam dicta quae consequatur ipsum a quo, explicabo asperiores, deleniti suscipit! Ullam adipisci, ea sint nobis vel debitis tempora fugit voluptate quo nulla molestias incidunt, esse, perspiciatis corrupti praesentium alias eveniet numquam. Totam, tempore. Voluptatibus, suscipit perferendis? Quisquam aliquid modi enim ipsam at maiores. Quibusdam dolores sunt et temporibus nobis, consectetur doloribus praesentium maxime impedit. Repellat voluptatibus veniam alias cumque possimus quibusdam! Illo, earum quo sit non voluptate at, sequi perferendis est dignissimos error nobis. Ipsum nobis nam rerum, ratione natus blanditiis explicabo deleniti perspiciatis excepturi cumque sapiente quis possimus? Cum, deserunt voluptas quaerat consectetur officiis autem non iure aspernatur?
       <ImgComp />
       Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est dignissimos explicabo dolorem accusantium excepturi? Quibusdam, nesciunt maiores excepturi mollitia nam atque voluptate corporis sapiente? Non aperiam corrupti natus laudantium cum delectus cumque!
       <ImgComp />
       Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam doloribus eius eos! Sed ea error temporibus omnis aspernatur, nostrum atque in quis quia, non repellat. Praesentium accusamus reprehenderit similique. Esse, omnis consequatur.
       <ImgComp />
       Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque, tenetur, culpa aut cupiditate ipsum sint hic iste provident minus accusantium, vitae eos esse modi libero facere nesciunt saepe fugit illum voluptatum inventore!
    </div>
  )
}

export default Home;